import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { RuleEngine, DEFAULT_NUMEROLOGY_RULES } from '../lib/rules/rule-engine.ts';
import { LUOSHU_GRID, getHeTuPartner, evaluateElementRelationship } from '../lib/numerology/digit-foundation.ts';

describe('ZWTSP Digit Foundation & Numerology Rules Tests', () => {
  const engine = new RuleEngine(DEFAULT_NUMEROLOGY_RULES);

  test('0-9 Digit to Element mapping matches canonical specification', () => {
    const expected = {
      0: 'Earth',
      1: 'Water',
      2: 'Fire',
      3: 'Wood',
      4: 'Metal',
      5: 'Earth',
      6: 'Water',
      7: 'Fire',
      8: 'Wood',
      9: 'Metal',
    };

    for (let d = 0; d <= 9; d++) {
      const el = engine.getDigitElement(d);
      assert.equal(el, expected[d], `Digit ${d} must map to ${expected[d]}, got ${el}`);
    }
  });

  test('Yin / Yang Polarity rules (Odd=Yang, Even=Yin)', () => {
    for (let d = 0; d <= 9; d++) {
      const pol = engine.getDigitPolarity(d);
      const expected = d % 2 === 1 ? 'Yang' : 'Yin';
      assert.equal(pol, expected, `Digit ${d} polarity must be ${expected}`);
    }
  });

  test('He Tu pairs verification (1-6, 2-7, 3-8, 4-9, 5-0)', () => {
    assert.equal(engine.getHeTuPartner(1), 6);
    assert.equal(engine.getHeTuPartner(6), 1);
    assert.equal(engine.getHeTuPartner(2), 7);
    assert.equal(engine.getHeTuPartner(7), 2);
    assert.equal(engine.getHeTuPartner(3), 8);
    assert.equal(engine.getHeTuPartner(8), 3);
    assert.equal(engine.getHeTuPartner(4), 9);
    assert.equal(engine.getHeTuPartner(9), 4);
    assert.equal(engine.getHeTuPartner(5), 0);
    assert.equal(engine.getHeTuPartner(0), 5);
  });

  test('Luo Shu 3x3 Magic Square properties', () => {
    // 4 9 2
    // 3 5 7
    // 8 1 6
    const row1 = LUOSHU_GRID[4].digit + LUOSHU_GRID[9].digit + LUOSHU_GRID[2].digit;
    const row2 = LUOSHU_GRID[3].digit + LUOSHU_GRID[5].digit + LUOSHU_GRID[7].digit;
    const row3 = LUOSHU_GRID[8].digit + LUOSHU_GRID[1].digit + LUOSHU_GRID[6].digit;

    const col1 = LUOSHU_GRID[4].digit + LUOSHU_GRID[3].digit + LUOSHU_GRID[8].digit;
    const col2 = LUOSHU_GRID[9].digit + LUOSHU_GRID[5].digit + LUOSHU_GRID[1].digit;
    const col3 = LUOSHU_GRID[2].digit + LUOSHU_GRID[7].digit + LUOSHU_GRID[6].digit;

    const diag1 = LUOSHU_GRID[4].digit + LUOSHU_GRID[5].digit + LUOSHU_GRID[6].digit;
    const diag2 = LUOSHU_GRID[2].digit + LUOSHU_GRID[5].digit + LUOSHU_GRID[8].digit;

    assert.equal(row1, 15);
    assert.equal(row2, 15);
    assert.equal(row3, 15);
    assert.equal(col1, 15);
    assert.equal(col2, 15);
    assert.equal(col3, 15);
    assert.equal(diag1, 15);
    assert.equal(diag2, 15);
  });

  test('Five Element generating and overcoming compatibility function', () => {
    // Wood generates Fire
    const woodFire = evaluateElementRelationship('Wood', 'Fire');
    assert.equal(woodFire.relation, 'generates');
    assert.equal(woodFire.score, 90);

    // Fire generated by Wood
    const fireWood = evaluateElementRelationship('Fire', 'Wood');
    assert.equal(fireWood.relation, 'generated_by');
    assert.equal(fireWood.score, 100);

    // Wood overcomes Earth
    const woodEarth = evaluateElementRelationship('Wood', 'Earth');
    assert.equal(woodEarth.relation, 'overcomes');
    assert.equal(woodEarth.score, 50);

    // Earth overcome by Wood
    const earthWood = evaluateElementRelationship('Earth', 'Wood');
    assert.equal(earthWood.relation, 'overcome_by');
    assert.equal(earthWood.score, 30);

    // Same Element (Water - Water)
    const waterWater = evaluateElementRelationship('Water', 'Water');
    assert.equal(waterWater.relation, 'same');
    assert.equal(waterWater.score, 85);
  });
});
