// ==========================================================
// 紫微时空数字预测系统 (ZWTSP) Daily Time-Space Activation Engine
// File: lib/engines/daily/daily-engine.ts
// ==========================================================

import type {
  DailyNumberActivation,
  DailyPalaceActivation,
  DailyTimeSignature,
  OpportunityLevel,
  PersonalNumberDNA,
  WuXingElement,
  ZiWeiChartData,
} from '../../../types/zwtsp.ts';
import { CalendarConversionEngine, BRANCH_ELEMENTS, STEM_ELEMENTS } from '../calendar/calendar-engine.ts';
import { SolarTermEngine } from '../calendar/solar-terms.ts';
import { FOUR_TRANSFORMATIONS_BY_STEM } from '../ziwei/ziwei-engine.ts';
import { getDigitElement, evaluateElementRelationship } from '../../numerology/digit-foundation.ts';

export class DailyEngine {
  public static readonly VERSION = 'DAILY-V2.0';

  /**
   * Generates complete Daily Time Signature for a given Gregorian date and timezone
   */
  public static generateDailySignature(dateStr: string, timezone: string = 'Asia/Shanghai'): DailyTimeSignature {
    const lunar = CalendarConversionEngine.toLunarDate(dateStr);
    const solarTerm = SolarTermEngine.getSolarTermInfo(dateStr);
    const fourPillars = CalendarConversionEngine.getFourPillars(dateStr, '10:00:00', true);

    // Calculate Daily Five Elements Signature (0-100)
    // Daily commander: Day Stem (35 pts) + Day Branch (30 pts) + Month (15 pts) + Season (10 pts)
    const elementScores: Record<WuXingElement, number> = {
      Wood: 15, Fire: 15, Earth: 15, Metal: 15, Water: 15,
    };

    // Seasonal background (+10 pts)
    const seasonMap: Record<string, WuXingElement> = {
      Spring: 'Wood', Summer: 'Fire', Autumn: 'Metal', Winter: 'Water', FourSeasonsEnd: 'Earth'
    };
    elementScores[seasonMap[solarTerm.season]] += 10;

    // Day Stem is the daily commander (+35 pts)
    const dayStemEl = STEM_ELEMENTS[fourPillars.dayStem] || fourPillars.dayElement || 'Fire';
    elementScores[dayStemEl] += 35;

    // Day Branch is the earthly foundation (+30 pts)
    const dayBranchEl = BRANCH_ELEMENTS[fourPillars.dayBranch] || 'Earth';
    elementScores[dayBranchEl] += 30;

    // Month Stem/Branch (+15 pts)
    elementScores[fourPillars.monthElement] += 15;

    // Normalize element scores to 0-100 range
    let dominantElement: WuXingElement = 'Metal';
    let maxScore = -1;
    let weakElement: WuXingElement = 'Wood';
    let minScore = 999;

    for (const [el, raw] of Object.entries(elementScores) as [WuXingElement, number][]) {
      const clamped = Math.min(100, Math.max(10, raw));
      elementScores[el] = clamped;
      if (clamped > maxScore) {
        maxScore = clamped;
        dominantElement = el;
      }
      if (clamped < minScore) {
        minScore = clamped;
        weakElement = el;
      }
    }

    // Secondary element: generates dominant or is generated by dominant
    const secondaryMap: Record<WuXingElement, WuXingElement> = {
      Wood: 'Water', Fire: 'Wood', Earth: 'Fire', Metal: 'Earth', Water: 'Metal',
    };
    const secondaryElement = secondaryMap[dominantElement];

    // Calculate Opportunity Score & Level
    const baseOpportunity = Math.round(55 + (elementScores[dominantElement] * 0.3));
    const opportunityScore = Math.min(100, Math.max(25, baseOpportunity));
    const opportunityLevel = this.classifyLevel(opportunityScore);

    return {
      date: dateStr,
      timezone,
      gregorianDate: `${dateStr} (${timezone})`,
      lunarDate: lunar.lunarString,
      solarTerm,
      yearStemBranch: `${fourPillars.yearStem}${fourPillars.yearBranch}年`,
      monthStemBranch: `${fourPillars.monthStem}${fourPillars.monthBranch}月`,
      dayStemBranch: `${fourPillars.dayStem}${fourPillars.dayBranch}日`,
      dayStem: fourPillars.dayStem,
      dayBranch: fourPillars.dayBranch,
      hourStemBranch: `${fourPillars.hourStem || '丙'}${fourPillars.hourBranch || '午'}时`,
      woodScore: elementScores.Wood,
      fireScore: elementScores.Fire,
      earthScore: elementScores.Earth,
      metalScore: elementScores.Metal,
      waterScore: elementScores.Water,
      dominantElement,
      secondaryElement,
      weakElement,
      opportunityScore,
      opportunityLevel,
      primaryWindow: '巳时 (09:00 - 11:00) · 气清神敛',
      secondaryWindow: '申时 (15:00 - 17:00) · 金水相生',
      avoidWindow: '午时 (11:00 - 13:00) · 烈阳冲克',
      calculationVersion: this.VERSION,
    };
  }

  /**
   * Activates 12 Palaces dynamically against today's time signature & Daily ZiWei Flying Stars (流日四化)
   */
  public static activatePalaces(chart: ZiWeiChartData, sig: DailyTimeSignature): DailyPalaceActivation[] {
    const results: DailyPalaceActivation[] = [];
    const dayStem = sig.dayStem || (sig.dayStemBranch ? sig.dayStemBranch.replace('日', '')[0] : '甲');
    const dailySiHua = FOUR_TRANSFORMATIONS_BY_STEM[dayStem] || { Lu: '廉贞', Quan: '破军', Ke: '武曲', Ji: '太阳' };

    for (const p of chart.palaces) {
      const elRel = evaluateElementRelationship(p.element, sig.dominantElement);
      let elementScore = 50;
      if (elRel.relation === 'same') elementScore = 85;
      else if (elRel.relation === 'generated_by') elementScore = 95;
      else if (elRel.relation === 'generates') elementScore = 75;
      else elementScore = 40;

      // Key palace boosts
      let palaceBonus = 0;
      if (p.palaceName === '财帛宫') palaceBonus = 12;
      else if (p.palaceName === '迁移宫') palaceBonus = 10;
      else if (p.palaceName === '福德宫') palaceBonus = 8;
      else if (p.palaceName === '命宫') palaceBonus = 8;

      // Birth Transformation bonus
      let transBonus = 0;
      for (const t of p.transformations) {
        if (t.transformation === 'Lu') transBonus += 10;
        if (t.transformation === 'Quan') transBonus += 7;
        if (t.transformation === 'Ke') transBonus += 5;
        if (t.transformation === 'Ji') transBonus -= 8;
      }

      // Dynamic Daily SiHua Flying Star Boost (流日四化飞星加持)
      let dailySiHuaBonus = 0;
      const palaceStarNames = p.stars ? p.stars.map((s) => s.starName) : [];
      if (palaceStarNames.includes(dailySiHua.Lu)) dailySiHuaBonus += 25; // 流日化禄飞入本宫
      if (palaceStarNames.includes(dailySiHua.Quan)) dailySiHuaBonus += 18; // 流日化权飞入本宫
      if (palaceStarNames.includes(dailySiHua.Ke)) dailySiHuaBonus += 12; // 流日化科飞入本宫
      if (palaceStarNames.includes(dailySiHua.Ji)) dailySiHuaBonus -= 15; // 流日化忌飞入本宫

      const activationScore = Math.min(
        100,
        Math.max(15, Math.round(50 * 0.2 + elementScore * 0.4 + palaceBonus + transBonus + dailySiHuaBonus))
      );
      const status = this.classifyLevel(activationScore);

      results.push({
        palaceName: p.palaceName,
        baseScore: p.score || 50,
        timeScore: 70,
        elementScore,
        starScore: 65,
        transformationScore: 50 + transBonus + dailySiHuaBonus,
        activationScore,
        status,
      });
    }

    // Sort descending by activation score
    return results.sort((a, b) => b.activationScore - a.activationScore);
  }

  /**
   * Dynamic Personal Daily Activation of Digits 0-9:
   * Personal DNA × Daily Time Structure × Daily Stem/Branch Resonance
   */
  public static activateNumbers(
    dna: PersonalNumberDNA,
    palaces: DailyPalaceActivation[],
    sig: DailyTimeSignature
  ): DailyNumberActivation[] {
    const activations: DailyNumberActivation[] = [];

    const activePalaceMap = new Map(palaces.map(p => [p.palaceName, p.activationScore]));
    const wealthPalaceScore = activePalaceMap.get('财帛宫') || 50;
    const movePalaceScore = activePalaceMap.get('迁移宫') || 50;
    const topPalace = palaces[0];

    const dayStem = sig.dayStem || (sig.dayStemBranch ? sig.dayStemBranch.replace('日', '')[0] : '甲');
    const STEM_NUMS: Record<string, number[]> = {
      甲: [1, 6, 9], 乙: [2, 7, 8], 丙: [3, 8, 7], 丁: [4, 9, 6], 戊: [5, 0, 5],
      己: [5, 0, 9], 庚: [4, 9, 8], 辛: [1, 6, 7], 壬: [1, 6, 6], 癸: [2, 7, 5],
    };
    const dayNums = STEM_NUMS[dayStem] || [];

    for (let d = 0; d <= 9; d++) {
      const personalBase = dna.scoresByDigit[d] || 50;
      const el = getDigitElement(d);

      // Element score in daily signature
      const dailyElementScore = sig[`${el.toLowerCase()}Score` as keyof DailyTimeSignature] as number || 50;

      // Time harmony score
      const timeRel = evaluateElementRelationship(el, sig.dominantElement);
      const timeScore = timeRel.score;

      // Palace boost
      const palaceScore = Math.round((wealthPalaceScore * 0.6) + (movePalaceScore * 0.4));

      // Daily Stem Auspicious Resonance
      let stemResonanceBonus = dayNums.includes(d) ? 20 : 0;
      if (topPalace && activePalaceMap.get(topPalace.palaceName) && activePalaceMap.get(topPalace.palaceName)! > 70) {
        stemResonanceBonus += 5;
      }

      // Star & transformation bonus
      const starScore = dna.coreNumbers.includes(d) ? 80 : 55;
      const transformationScore = dna.coreNumbers.includes(d) ? 75 : 50;

      // Dynamic weighted activation formula: 80% Time/Space + 20% Personal Base
      const rawActivation =
        personalBase * 0.20 +
        dailyElementScore * 0.30 +
        timeScore * 0.25 +
        palaceScore * 0.15 +
        stemResonanceBonus;

      const activationScore = Math.min(100, Math.max(10, Math.round(rawActivation)));

      activations.push({
        digit: d,
        personalBaseScore: personalBase,
        elementScore: dailyElementScore,
        timeScore,
        palaceScore,
        starScore,
        transformationScore,
        activationScore,
        rank: 0, // will be assigned after sorting
        classification: 'Secondary',
        trace: [
          { factor: '本命基因基准 (Personal Base)', description: `静态本命数理基准`, points: Math.round(personalBase * 0.20) },
          { factor: `今日五行场能 (${el})`, description: `当日五行得分: ${dailyElementScore}`, points: Math.round(dailyElementScore * 0.30) },
          { factor: `时空日干生克共振`, description: `${timeRel.label} · 流日干支气机`, points: Math.round(timeScore * 0.25) },
          { factor: `活跃宫位加持 (财帛/迁移)`, description: `活跃宫位均分: ${palaceScore}`, points: Math.round(palaceScore * 0.15) },
          { factor: `流日干支飞星神数`, description: `流日值符天机调摄`, points: stemResonanceBonus },
        ],
      });
    }

    // Sort descending by activation score
    activations.sort((a, b) => b.activationScore - a.activationScore);

    // Assign ranks and classifications
    activations.forEach((act, idx) => {
      act.rank = idx + 1;
      if (idx < 3) act.classification = 'Primary'; // Top 3
      else if (idx < 7) act.classification = 'Secondary'; // Next 4
      else act.classification = 'Weak'; // Bottom 3
    });

    return activations;
  }

  /**
   * Computes Opportunity Score (0-100) per Section 23 specification
   */
  public static calculateOpportunityScore(
    topActivationAvg: number,
    dailySigScore: number,
    palaces: DailyPalaceActivation[]
  ): { score: number; level: OpportunityLevel; cautionNotice?: string } {
    const palaceMap = new Map(palaces.map(p => [p.palaceName, p.activationScore]));
    const defaultProxy = palaces.length > 0 ? 50 : topActivationAvg;
    const financialScore = palaceMap.get('财帛宫') ?? defaultProxy;
    const fortuneScore = palaceMap.get('福德宫') ?? defaultProxy;
    const lifeScore = palaceMap.get('命宫') ?? defaultProxy;
    const movementScore = palaceMap.get('迁移宫') ?? defaultProxy;
    const transScore = palaces.length > 0 ? 75 : defaultProxy;

    // Formula:
    // Personal Daily Activation: 25%
    // Daily Time Signature: 20%
    // Financial Palace Activation: 20%
    // Fortune Palace Activation: 10%
    // Life Palace Activation: 10%
    // Movement Palace Activation: 5%
    // Transformation Activation: 10%
    const totalScore = Math.round(
      topActivationAvg * 0.25 +
      dailySigScore * 0.20 +
      financialScore * 0.20 +
      fortuneScore * 0.10 +
      lifeScore * 0.10 +
      movementScore * 0.05 +
      transScore * 0.10
    );

    const score = Math.min(100, Math.max(10, totalScore));
    const level = this.classifyLevel(score);

    let cautionNotice: string | undefined;
    if (score < 40) {
      cautionNotice = '今日模型状态偏低，建议保持观察，不因系统增加投注。';
    }

    return { score, level, cautionNotice };
  }

  public static classifyLevel(score: number): OpportunityLevel {
    if (score < 30) return 'LOW';
    if (score < 50) return 'WEAK';
    if (score < 70) return 'NORMAL';
    if (score < 85) return 'STRONG';
    return 'VERY STRONG';
  }
}
