// ==========================================================
// 紫微时空数字预测系统 (ZWTSP) Daily Time-Space Activation Engine
// File: lib/engines/daily/daily-engine.ts
// ==========================================================

import type {
  DailyNumberActivation,
  DailyPalaceActivation,
  DailyTimeSignature,
  OpportunityLevel,
  PersonalNumberDNA,
  WuXingElement,
  ZiWeiChartData,
} from '../../../types/zwtsp.ts';
import { CalendarConversionEngine } from '../calendar/calendar-engine.ts';
import { SolarTermEngine } from '../calendar/solar-terms.ts';
import { getDigitElement, evaluateElementRelationship } from '../../numerology/digit-foundation.ts';

export class DailyEngine {
  public static readonly VERSION = 'DAILY-V1.0';

  /**
   * Generates complete Daily Time Signature for a given Gregorian date and timezone
   */
  public static generateDailySignature(dateStr: string, timezone: string = 'Asia/Shanghai'): DailyTimeSignature {
    const lunar = CalendarConversionEngine.toLunarDate(dateStr);
    const solarTerm = SolarTermEngine.getSolarTermInfo(dateStr);
    const fourPillars = CalendarConversionEngine.getFourPillars(dateStr, '10:00:00', true);

    // Calculate Daily Five Elements Signature (0-100)
    // Dynamic weights: Season 35% + Day Stem/Branch 35% + Month Branch 20% + Year 10%
    const elementScores: Record<WuXingElement, number> = {
      Wood: 15, Fire: 15, Earth: 15, Metal: 15, Water: 15,
    };

    // Seasonal boost (+35 pts)
    const seasonMap: Record<string, WuXingElement> = {
      Spring: 'Wood', Summer: 'Fire', Autumn: 'Metal', Winter: 'Water', FourSeasonsEnd: 'Earth'
    };
    elementScores[seasonMap[solarTerm.season]] += 35;

    // Day Stem & Branch (+30 pts)
    elementScores[fourPillars.dayElement] += 18;
    const dayBranchEl = fourPillars.elementDistribution[fourPillars.dayElement] ? fourPillars.dayElement : 'Earth';
    elementScores[dayBranchEl] += 12;

    // Month Stem/Branch (+20 pts)
    elementScores[fourPillars.monthElement] += 20;

    // Normalize element scores to 0-100 range
    let dominantElement: WuXingElement = 'Metal';
    let maxScore = -1;
    let weakElement: WuXingElement = 'Wood';
    let minScore = 999;

    for (const [el, raw] of Object.entries(elementScores) as [WuXingElement, number][]) {
      const clamped = Math.min(100, Math.max(10, raw));
      elementScores[el] = clamped;
      if (clamped > maxScore) {
        maxScore = clamped;
        dominantElement = el;
      }
      if (clamped < minScore) {
        minScore = clamped;
        weakElement = el;
      }
    }

    // Secondary element: generates dominant or is generated by dominant
    const secondaryMap: Record<WuXingElement, WuXingElement> = {
      Wood: 'Water', Fire: 'Wood', Earth: 'Fire', Metal: 'Earth', Water: 'Metal',
    };
    const secondaryElement = secondaryMap[dominantElement];

    // Calculate Opportunity Score & Level
    const baseOpportunity = Math.round(55 + (elementScores[dominantElement] * 0.3));
    const opportunityScore = Math.min(100, Math.max(25, baseOpportunity));
    const opportunityLevel = this.classifyLevel(opportunityScore);

    return {
      date: dateStr,
      timezone,
      gregorianDate: `${dateStr} (${timezone})`,
      lunarDate: lunar.lunarString,
      solarTerm,
      yearStemBranch: `${fourPillars.yearStem}${fourPillars.yearBranch}年`,
      monthStemBranch: `${fourPillars.monthStem}${fourPillars.monthBranch}月`,
      dayStemBranch: `${fourPillars.dayStem}${fourPillars.dayBranch}日`,
      hourStemBranch: `${fourPillars.hourStem || '丙'}${fourPillars.hourBranch || '午'}时`,
      woodScore: elementScores.Wood,
      fireScore: elementScores.Fire,
      earthScore: elementScores.Earth,
      metalScore: elementScores.Metal,
      waterScore: elementScores.Water,
      dominantElement,
      secondaryElement,
      weakElement,
      opportunityScore,
      opportunityLevel,
      primaryWindow: '巳时 (09:00 - 11:00) · 气清神敛',
      secondaryWindow: '申时 (15:00 - 17:00) · 金水相生',
      avoidWindow: '午时 (11:00 - 13:00) · 烈阳冲克',
      calculationVersion: this.VERSION,
    };
  }

  /**
   * Activates 12 Palaces dynamically against today's time signature
   */
  public static activatePalaces(chart: ZiWeiChartData, sig: DailyTimeSignature): DailyPalaceActivation[] {
    const results: DailyPalaceActivation[] = [];

    for (const p of chart.palaces) {
      const elRel = evaluateElementRelationship(p.element, sig.dominantElement);
      let elementScore = 50;
      if (elRel.relation === 'same') elementScore = 85;
      else if (elRel.relation === 'generated_by') elementScore = 95;
      else if (elRel.relation === 'generates') elementScore = 75;
      else elementScore = 40;

      // Key palace boosts
      let palaceBonus = 0;
      if (p.palaceName === '财帛宫') palaceBonus = 12;
      else if (p.palaceName === '迁移宫') palaceBonus = 10;
      else if (p.palaceName === '福德宫') palaceBonus = 8;
      else if (p.palaceName === '命宫') palaceBonus = 6;

      // Transformation bonus
      let transBonus = 0;
      for (const t of p.transformations) {
        if (t.transformation === 'Lu') transBonus += 15;
        if (t.transformation === 'Quan') transBonus += 10;
        if (t.transformation === 'Ke') transBonus += 8;
        if (t.transformation === 'Ji') transBonus -= 12;
      }

      const activationScore = Math.min(100, Math.max(15, Math.round(50 * 0.3 + elementScore * 0.4 + palaceBonus + transBonus)));
      const status = this.classifyLevel(activationScore);

      results.push({
        palaceName: p.palaceName,
        baseScore: p.score || 50,
        timeScore: 70,
        elementScore,
        starScore: 65,
        transformationScore: 50 + transBonus,
        activationScore,
        status,
      });
    }

    // Sort descending by activation score
    return results.sort((a, b) => b.activationScore - a.activationScore);
  }

  /**
   * Dynamic Personal Daily Activation of Digits 0-9:
   * Personal DNA × Daily Time Structure
   */
  public static activateNumbers(
    dna: PersonalNumberDNA,
    palaces: DailyPalaceActivation[],
    sig: DailyTimeSignature
  ): DailyNumberActivation[] {
    const activations: DailyNumberActivation[] = [];

    const activePalaceMap = new Map(palaces.map(p => [p.palaceName, p.activationScore]));
    const wealthPalaceScore = activePalaceMap.get('财帛宫') || 50;
    const movePalaceScore = activePalaceMap.get('迁移宫') || 50;

    for (let d = 0; d <= 9; d++) {
      const personalBase = dna.scoresByDigit[d] || 50;
      const el = getDigitElement(d);

      // Element score in daily signature
      const dailyElementScore = sig[`${el.toLowerCase()}Score` as keyof DailyTimeSignature] as number || 50;

      // Time harmony score
      const timeRel = evaluateElementRelationship(el, sig.dominantElement);
      const timeScore = timeRel.score;

      // Palace boost
      const palaceScore = Math.round((wealthPalaceScore * 0.6) + (movePalaceScore * 0.4));

      // Star & transformation bonus
      const starScore = dna.coreNumbers.includes(d) ? 88 : 55;
      const transformationScore = dna.coreNumbers.includes(d) ? 80 : 50;

      // Dynamic weighted activation formula
      // 35% Personal Base + 25% Daily Element + 15% Daily Time + 15% Palace + 10% Star
      const rawActivation =
        personalBase * 0.35 +
        dailyElementScore * 0.25 +
        timeScore * 0.15 +
        palaceScore * 0.15 +
        starScore * 0.10;

      const activationScore = Math.min(100, Math.max(10, Math.round(rawActivation)));

      activations.push({
        digit: d,
        personalBaseScore: personalBase,
        elementScore: dailyElementScore,
        timeScore,
        palaceScore,
        starScore,
        transformationScore,
        activationScore,
        rank: 0, // will be assigned after sorting
        classification: 'Secondary',
        trace: [
          { factor: '本命基因基准 (Personal Base)', description: `静态本命数理基准`, points: Math.round(personalBase * 0.35) },
          { factor: `今日五行场能 (${el})`, description: `当日五行得分: ${dailyElementScore}`, points: Math.round(dailyElementScore * 0.25) },
          { factor: `时空生克共振`, description: `${timeRel.label} (时律评分配比)`, points: Math.round(timeScore * 0.15) },
          { factor: `活跃宫位加持 (财帛/迁移)`, description: `活跃宫位均分: ${palaceScore}`, points: Math.round(palaceScore * 0.15) },
          { factor: `星曜格局催发`, description: `主星四化气机调摄`, points: Math.round(starScore * 0.10) },
        ],
      });
    }

    // Sort descending by activation score
    activations.sort((a, b) => b.activationScore - a.activationScore);

    // Assign ranks and classifications
    activations.forEach((act, idx) => {
      act.rank = idx + 1;
      if (idx < 3) act.classification = 'Primary'; // Top 3
      else if (idx < 7) act.classification = 'Secondary'; // Next 4
      else act.classification = 'Weak'; // Bottom 3
    });

    return activations;
  }

  /**
   * Computes Opportunity Score (0-100) per Section 23 specification
   */
  public static calculateOpportunityScore(
    topActivationAvg: number,
    dailySigScore: number,
    palaces: DailyPalaceActivation[]
  ): { score: number; level: OpportunityLevel; cautionNotice?: string } {
    const palaceMap = new Map(palaces.map(p => [p.palaceName, p.activationScore]));
    const defaultProxy = palaces.length > 0 ? 50 : topActivationAvg;
    const financialScore = palaceMap.get('财帛宫') ?? defaultProxy;
    const fortuneScore = palaceMap.get('福德宫') ?? defaultProxy;
    const lifeScore = palaceMap.get('命宫') ?? defaultProxy;
    const movementScore = palaceMap.get('迁移宫') ?? defaultProxy;
    const transScore = palaces.length > 0 ? 75 : defaultProxy;

    // Formula:
    // Personal Daily Activation: 25%
    // Daily Time Signature: 20%
    // Financial Palace Activation: 20%
    // Fortune Palace Activation: 10%
    // Life Palace Activation: 10%
    // Movement Palace Activation: 5%
    // Transformation Activation: 10%
    const totalScore = Math.round(
      topActivationAvg * 0.25 +
      dailySigScore * 0.20 +
      financialScore * 0.20 +
      fortuneScore * 0.10 +
      lifeScore * 0.10 +
      movementScore * 0.05 +
      transScore * 0.10
    );

    const score = Math.min(100, Math.max(10, totalScore));
    const level = this.classifyLevel(score);

    let cautionNotice: string | undefined;
    if (score < 40) {
      cautionNotice = '今日模型状态偏低，建议保持观察，不因系统增加投注。';
    }

    return { score, level, cautionNotice };
  }

  public static classifyLevel(score: number): OpportunityLevel {
    if (score < 30) return 'LOW';
    if (score < 50) return 'WEAK';
    if (score < 70) return 'NORMAL';
    if (score < 85) return 'STRONG';
    return 'VERY STRONG';
  }
}
